inherit_from: .rubocop.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Tắt các luật về độ dài dòng và chú thích tiếng Việt (để tránh lỗi layout)
Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false